### ISSUE TITLE
My great great great grandmother's and grand grand granddaughter's ee ID is not recognized

### ISSUE THREAD

**Issue by rannooo** [rematocorp/personal-code-to-birthday#1]
https://github.com/rematocorp/personal-code-to-birthday/blob/5b587a81e49f21d02c256531e7a4d2016b0d3f41/src/parsers/estoniaLithuania.ts#L10

I found a relic smart-id signed document from old church archives and saw that my great great great grandmother's ID code was 29212035722 and I really wanted to know when she was born but unfortunately this library does not respect my grandmother.
Also I talked to Urmas Sõõrumaa who modelled my astronomical projection body and I got the cosmic knowledge that my grand grand grand granddaughter's ID code will be 89212035722 and I also really wanted to know at what date she will be born but this library failed to provide me answers.

Sir Mr Puku Attack please help me, you are my only and last option to solve these mysteries.

**Comment by ukupat** [comment]
I will think about it :D
